apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nodejs-app.fullname" . }}
  labels:
{{- include "nodejs-app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
{{- include "nodejs-app.selectorLabels" . | nindent 6 }}
